# Generated by Django 3.2.16 on 2025-02-08 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='is_published*')),
                ('created_at', models.DateTimeField(verbose_name='created_at*')),
                ('title', models.CharField(max_length=256, verbose_name='title*')),
                ('description', models.TextField(verbose_name='description*')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Слаг*')),
            ],
            options={
                'verbose_name': 'Тематическая категория',
                'verbose_name_plural': 'Тематические категории',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='is_published*')),
                ('created_at', models.DateTimeField(verbose_name='created_at*')),
                ('name', models.CharField(max_length=256, verbose_name='name*')),
            ],
            options={
                'verbose_name': 'Географическая метка',
                'verbose_name_plural': 'Географические метки',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='is_published*')),
                ('created_at', models.DateTimeField(verbose_name='created_at*')),
                ('title', models.CharField(max_length=256, verbose_name='title*')),
                ('text', models.TextField(verbose_name='text*')),
                ('pub_date', models.DateTimeField(verbose_name='pub_date*')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='author**')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.category', verbose_name='category**')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.location', verbose_name='location**')),
            ],
            options={
                'verbose_name': 'Публикация*',
                'verbose_name_plural': 'Публикации*',
            },
        ),
    ]
