# Generated by Django 3.2.16 on 2025-03-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250306_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='---Пусто---', verbose_name='Текст комментария'),
        ),
    ]
